# Generated by Django 5.1.1 on 2024-09-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_register_email_alter_register_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
